[env:esp32c3]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
board_build.mcu = esp32c3
lib_deps = 
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    tzapu/WiFiManager@^2.0.17
